=pod

=head1 NAME

Geo::UK::Postcode::Manual::Geolocation

=head1 DESCRIPTION

Instructions on how to use the OS Code-Point data, with or without
L<Geo::UK::Postcode>.

=head1 INSTRUCTIONS

=over

=item * Download OS Code Point Open data

L<https://www.ordnancesurvey.co.uk/opendatadownload/products.html>

Select 'Download' checkbox for Code-Point Open, enter your details on the
form on the next page, and wait for the email.

=back


=cut

